### ISSUE TITLE
Predictable friendly fire issue with Requiem

### ISSUE THREAD

**Issue by AeiouEnigma** [stormdirus2/nox#3]
Requiem allows players to possess and control various mobs, especially zombies and skeletons. A player who is possessing a zombie cannot directly damage or be damaged by other monsters.

**Comment by stormdirus2** [comment]
Is this verified or is this speculation?

Currently the way the friendly fire check works is by comparing the monsters' targets. So if they have differing targets, they will still take damage from each other.

**Comment by AeiouEnigma** [comment]
Even in general, I think it would be best to default to vanilla friendly fire behavior. It feels clunky to me to have projectiles pass through entities, and it would be very frustrating to have a player be hit by an arrow from a skeleton who's obstructed by other entities.

It's not speculation. I've tested it just now.

**Comment by AeiouEnigma** [comment]
It seemed a bit inconsistent though. I know Requiem can complicate this stuff.

**Comment by AeiouEnigma** [comment]
It seems that a possessing player can attack monsters once. After that point, the monsters attempt to attack the player and fail to inflict any damage. The player is also unable to inflict further harm on the monsters.

**Comment by stormdirus2** [comment]
That is incredibly confusing. I'll need to test this. 

I'll find some way to patch this 🤔

**Comment by AeiouEnigma** [comment]
Possibly relevant issue: https://github.com/tr7zw/EntityCulling/issues/48

**Comment by stormdirus2** [comment]
Yup, this indeed does happen. 

So odd...
I'll do some more testing.

**Comment by stormdirus2** [comment]
LMAO

I found out why, now I'm going to bully Pyrofab. For some cursed reason, possessed mobs can target *themselves*.

**Comment by stormdirus2** [comment]
I have a fix, and it's non-invasive.

**Comment by AeiouEnigma** [comment]
Actually you know what, that came up before when I was talking with Pyro. It's allowed so that a Challenge can be completed by possessing a Zombified Piglin and having it kill itself, but he agreed that it should probably be restricted to just Zombified Piglins.

But then, surely that would still leave the problem with Nox, at least for Zombified Piglin possession.

**Comment by AeiouEnigma** [comment]
I actually don't quite understand how this would resolve the issue even if Requiem possessed mobs couldn't target themselves. Wouldn't other mobs still be able to target the possessed one?

**Comment by AeiouEnigma** [comment]
And they *should* be able to target the possessed mob. The problem is that with Nox, they can't damage the possessed mob because the possessed mob is a Monster, right?

At least, that's my understanding from looking at this https://github.com/stormdirus2/nox/blob/eeed671da1236f3a663c5ec326d1b70fcdee8ffa/src/main/java/net/scirave/nox/mixin/MobEntityMixin.java#L98

**Comment by AeiouEnigma** [comment]
That commit looks pretty solid :)

**Comment by stormdirus2** [comment]
> I actually don't quite understand how this would resolve the issue even if Requiem possessed mobs couldn't target themselves. Wouldn't other mobs still be able to target the possessed one?

There's and if statement here:

https://github.com/stormdirus2/nox/blob/eeed671da1236f3a663c5ec326d1b70fcdee8ffa/src/main/java/net/scirave/nox/mixin/MobEntityMixin.java#L100

If the other mob's target is the possessed mob, and the possessed mob's target is itself, then it will satisfy it because target1 == target2.

**Comment by stormdirus2** [comment]
[Fixed in this release](https://github.com/stormdirus2/nox/releases/tag/v1.0-beta.8)
